<div class="gallery media-gallery">
    <div id="lightSlider">
        <?php
    $galleryImages = $block->getGalleryImages();

    foreach ($galleryImages as $galleryImage) {
        $imageUrl = $galleryImage->getMediumImageUrl();
        $smallImageUrl = $galleryImage->getSmallImageUrl();

        if ($galleryImage->getMediaType() === 'external-video') {
            $thumbnailClass = 'video';
            $largeImageUrl = $galleryImage->getVideoUrl();
        } else {
            $thumbnailClass = 'image';
            $largeImageUrl = $galleryImage->getLargeImageUrl();
        } ?>
        <a href="<?php echo $largeImageUrl; ?>"
            data-thumb="<?php echo $smallImageUrl; ?>"
            data-thumb-class="<?php echo $thumbnailClass; ?>"
            data-sub-html="<?php echo $galleryImage->getLabel(); ?>">
            <img src="<?php echo $imageUrl; ?>"
                width="<?php echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>"
                height="<?php echo $block->getImageAttribute('product_page_image_medium', 'height'); ?>"
                alt="<?php echo $galleryImage->getLabel(); ?>" />
        </a>
        <?php
    }
    ?>
    </div>
</div>
<script>
    require(
        [
            'jquery',
            'Grindnu_Media/js/lightslider',
            'Grindnu_Media/js/lightgallery',
            'domReady!'
        ],
        function($, a, b) {
            require([
                    'Grindnu_Media/js/lg-video',
                    'Grindnu_Media/js/lg-zoom'
                ],
                function() {
                    window.mediaGallery = $('#lightSlider').lightSlider({
                        auto: false,
                        actualSize: true,
                        autoWidth: false,
                        gallery: true,
                        item: 1,
                        loop: true,
                        slideMargin: 0,
                        thumbItem: 6,
                        thumbWidth: <?php echo $block->getImageAttribute('product_page_image_small', 'width'); ?> ,
                        thumbHeight: <?php echo $block->getImageAttribute('product_page_image_small', 'height'); ?> ,
                        youtubePlayerParams: {
                            modestbranding: 1,
                            showinfo: 0,
                            controls: 0
                        },
                        zoom: true,
                        onSliderLoad: function(el) {
                            $('#lightSlider').css('visibility', 'visible');

                            el.lightGallery({
                                selector: '#lightSlider .lslide',
                                download: false
                            });
                        }
                    });
                }
            );
        });
</script>