<div class="gallery media-gallery">
    <div id="lightSlider">
        <?php
    $galleryImages = $block->getGalleryImages();

    foreach ($galleryImages as $galleryImage) {
        $imageUrl = $galleryImage->getMediumImageUrl();
        $smallImageUrl = $galleryImage->getSmallImageUrl();

        if ($galleryImage->getMediaType() === 'external-video') {
            $thumbnailClass = 'video';
            $largeImageUrl = $galleryImage->getVideoUrl();
        } else {
            $thumbnailClass = 'image';
            $largeImageUrl = $galleryImage->getLargeImageUrl();
        } ?>
        <a href="<?php echo $largeImageUrl; ?>"
            data-thumb="<?php echo $smallImageUrl; ?>"
            data-thumb-class="<?php echo $thumbnailClass; ?>"
            data-sub-html="<?php echo $galleryImage->getLabel(); ?>">
            <img <?php
                // data-src
                // as https://stackoverflow.com/questions/57674943/how-do-i-lazy-load-images-in-jquery-lightslider
                ?>
            data-src="<?php echo $imageUrl; ?>"
            src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
            alt="<?php echo $galleryImage->getLabel(); ?>"
            />
        </a>
        <?php
    }
    ?>
    </div>
</div>
<script>
    require(
        [
            'jquery',
            'Grindnu_Media/js/lightslider',
            'Grindnu_Media/js/lightgallery',
            'domReady!'
        ],
        function($, a, b) {
            require([
                    'Grindnu_Media/js/lg-video',
                    'Grindnu_Media/js/lg-zoom'
                ],
                function() {
                    $('#lightSlider').lightSlider({
                        autoWidth: true,
                        gallery: true,
                        item: 1,
                        loop: true,
                        slideMargin: 0,
                        thumbItem: 6,
                        zoom: true,
                        actualSize: true,
                        youtubePlayerParams: {
                            modestbranding: 1,
                            showinfo: 0,
                            controls: 0
                        },
                        onSliderLoad: function(el) {
                            el.lightGallery({
                                selector: '#lightSlider .lslide',
                                download: false
                            });

                            var showActiveSlides = function(entries) {
                                entries.forEach(function(entry) {
                                    if (entry.isIntersecting) {
                                        entry.target.src = entry.target.dataset.src;
                                        observer.unobserve(entry.target);
                                    }
                                });
                            };

                            var imageWidth = el.find("a").outerWidth() + "px";

                            var observer = new window.IntersectionObserver(showActiveSlides, {
                                root: el.parent()[0],
                                rootMargin: "0px " + imageWidth + " 0px " + imageWidth
                            });

                            el.find("a img").each(function() {
                                observer.observe(this);
                            });
                        }
                    });
                }
            );
        });
</script>