<?php

use Grindnu\Media\Helper\Data;

$dataHelper = $this->helper(Data::class);

?>
<div class="gallery media-gallery">
    <div id="lightSlider">
        <?php
    $galleryImages = $block->getGalleryImages();

    foreach ($galleryImages as $galleryImage) {
        $imageUrl = $galleryImage->getMediumImageUrl();
        $smallImageUrl = $galleryImage->getSmallImageUrl();

        if ($galleryImage->getMediaType() === 'external-video') {
            $thumbnailClass = 'video';
            $largeImageUrl = $galleryImage->getVideoUrl();
        } else {
            $thumbnailClass = 'image';
            $largeImageUrl = $galleryImage->getLargeImageUrl();
        } ?>
        <a href="<?php echo $largeImageUrl; ?>"
            data-thumb="<?php echo $smallImageUrl; ?>"
            data-thumb-class="<?php echo $thumbnailClass; ?>"
            data-sub-html="<?php echo $galleryImage->getLabel(); ?>">
            <img src="<?php echo $imageUrl; ?>"
                width="<?php echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>"
                height="<?php echo $block->getImageAttribute('product_page_image_medium', 'height'); ?>"
                alt="<?php echo $galleryImage->getLabel(); ?>" />
        </a>
        <?php
    }
    ?>
    </div>
</div>
<script>
    require(
        [
            'jquery',
            'lightSlider',
            'lightGallery',
            'domReady!'
        ],
        function($, a, b) {
            require([
                    'lightSliderVideo',
                    'lightSliderZoom'
                ],
                function() {
                    window.mediaGallery = $('#lightSlider').lightSlider({
                        auto: <?php echo (bool) $dataHelper->getConfig('grindnu_media/settings/auto_start'); ?> ,
                        actualSize: <?php echo (bool) $dataHelper->getConfig('grindnu_media/settings/actual_size'); ?> ,
                        autoWidth: <?php echo (bool) $dataHelper->getConfig('grindnu_media/settings/auto_width'); ?> ,
                        gallery: <?php echo (bool) $dataHelper->getConfig('grindnu_media/settings/allow_gallery'); ?> ,
                        item: <?php echo (int) $dataHelper->getConfig('grindnu_media/settings/start_position'); ?> ,
                        loop: <?php echo (bool) $dataHelper->getConfig('grindnu_media/settings/allow_loop'); ?> ,
                        slideMargin: <?php echo (int) $dataHelper->getConfig('grindnu_media/settings/slide_margin'); ?> ,
                        thumbItem: <?php echo (int) $dataHelper->getConfig('grindnu_media/settings/number_of_thumbnails'); ?> ,
                        thumbWidth: <?php echo $block->getImageAttribute('product_page_image_small', 'width'); ?> ,
                        thumbHeight: <?php echo $block->getImageAttribute('product_page_image_small', 'height'); ?> ,
                        youtubePlayerParams: {
                            modestbranding: <?php echo (int) $dataHelper->getConfig('grindnu_media/settings/youtube_modest_branding'); ?> ,
                            showinfo: <?php echo (int) $dataHelper->getConfig('grindnu_media/settings/youtube_show_info'); ?> ,
                            controls: <?php echo (int) $dataHelper->getConfig('grindnu_media/settings/youtube_controls'); ?>
                        },
                        zoom: <?php echo (bool) $dataHelper->getConfig('grindnu_media/settings/allow_zoom'); ?> ,
                        onSliderLoad: function(el) {
                            $('#lightSlider').css('visibility', 'visible');

                            el.lightGallery({
                                selector: '#lightSlider .lslide',
                                download: <?php echo (bool) $dataHelper->getConfig('grindnu_media/settings/allow_download'); ?> ,
                            });
                        }
                    });
                }
            );
        });
</script>